"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LocaleService_1 = require("./LocaleService");
var CurrencyService_1 = require("./CurrencyService");
var LocaleService_2 = require("./LocaleService");
exports.DefaultLocaleService = LocaleService_2.DefaultLocaleService;
var CurrencyService_2 = require("./CurrencyService");
exports.DefaultCurrencyService = CurrencyService_2.DefaultCurrencyService;
exports.currrency = new CurrencyService_1.DefaultCurrencyService();
exports.locale = new LocaleService_1.DefaultLocaleService();
